"""Initial migration with all tables

Revision ID: 0aab2d0e6db9
Revises: 
Create Date: 2025-11-03 22:38:18.040470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0aab2d0e6db9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('builder',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('average_rating', sa.DECIMAL(precision=3, scale=2), nullable=True),
    sa.Column('total_projects', sa.Integer(), nullable=True),
    sa.Column('hyperlink', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_builder_id'), 'builder', ['id'], unique=False)
    op.create_table('employee',
    sa.Column('unique_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('post', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('unique_id')
    )
    op.create_index(op.f('ix_manager_unique_id'), 'employee', ['unique_id'], unique=False)
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('total_contributions', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_user_user_id'), 'user', ['user_id'], unique=False)
    op.create_table('road',
    sa.Column('road_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('coordinates', sa.JSON(), nullable=False),
    sa.Column('cost', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('started_date', sa.Date(), nullable=False),
    sa.Column('ended_date', sa.Date(), nullable=True),
    sa.Column('builder_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('maintained_by', sa.Integer(), nullable=False),
    sa.Column('chief_engineer', sa.String(), nullable=False),
    sa.Column('date_verified', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['builder_id'], ['builder.id'], ),
    sa.ForeignKeyConstraint(['maintained_by'], ['builder.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.unique_id'], ),
    sa.PrimaryKeyConstraint('road_id')
    )
    op.create_index(op.f('ix_road_road_id'), 'road', ['road_id'], unique=False)
    op.create_table('rating',
    sa.Column('rating_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('road_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.DECIMAL(precision=2, scale=1), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['road_id'], ['road.road_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('rating_id')
    )
    op.create_index(op.f('ix_rating_rating_id'), 'rating', ['rating_id'], unique=False)
    op.create_table('review',
    sa.Column('review_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('road_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('media', sa.String(), nullable=True),
    sa.Column('tags', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['road_id'], ['road.road_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('review_id')
    )
    op.create_index(op.f('ix_review_review_id'), 'review', ['review_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_review_review_id'), table_name='review')
    op.drop_table('review')
    op.drop_index(op.f('ix_rating_rating_id'), table_name='rating')
    op.drop_table('rating')
    op.drop_index(op.f('ix_road_road_id'), table_name='road')
    op.drop_table('road')
    op.drop_index(op.f('ix_user_user_id'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_manager_unique_id'), table_name='employee')
    op.drop_table('employee')
    op.drop_index(op.f('ix_builder_id'), table_name='builder')
    op.drop_table('builder')
    # ### end Alembic commands ###
