"""Add authentication and user-employee relationship

Revision ID: de7a8ef1de41
Revises: 0aab2d0e6db9
Create Date: 2025-11-04 08:25:13.838468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de7a8ef1de41'
down_revision: Union[str, Sequence[str], None] = '0aab2d0e6db9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create refresh_token table
    op.create_table('refresh_token',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_token_id'), 'refresh_token', ['id'], unique=False)
    op.create_index(op.f('ix_refresh_token_token'), 'refresh_token', ['token'], unique=True)
    
    # Update employee table with batch_alter_table for SQLite compatibility
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('department', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('employee_code', sa.String(), nullable=True))
        batch_op.create_unique_constraint('uq_manager_employee_code', ['employee_code'])
        batch_op.create_unique_constraint('uq_manager_user_id', ['user_id'])
        batch_op.create_foreign_key('fk_manager_user_id', 'user', ['user_id'], ['user_id'])
        batch_op.drop_column('name')
    
    # Make user_id NOT NULL after adding it
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.alter_column('user_id', existing_type=sa.Integer(), nullable=False)
    
    # Update road table
    with op.batch_alter_table('road', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_verified', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('verification_code', sa.String(), nullable=True))
    
    # Update user table
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('hashed_password', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('user_type', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_verified', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('age', existing_type=sa.INTEGER(), nullable=True)
        batch_op.create_index('ix_user_email', ['email'], unique=True)
        batch_op.create_index('ix_user_phone', ['phone'], unique=True)
    
    # Make email and hashed_password NOT NULL after adding them
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('email', existing_type=sa.String(), nullable=False)
        batch_op.alter_column('hashed_password', existing_type=sa.String(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Revert user table changes
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('ix_user_phone')
        batch_op.drop_index('ix_user_email')
        batch_op.alter_column('age', existing_type=sa.INTEGER(), nullable=False)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('is_verified')
        batch_op.drop_column('is_active')
        batch_op.drop_column('user_type')
        batch_op.drop_column('hashed_password')
        batch_op.drop_column('phone')
        batch_op.drop_column('email')
    
    # Revert road table changes
    with op.batch_alter_table('road', schema=None) as batch_op:
        batch_op.drop_column('verification_code')
        batch_op.drop_column('is_verified')
    
    # Revert employee table changes
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(), nullable=False))
        batch_op.drop_constraint('fk_manager_user_id', type_='foreignkey')
        batch_op.drop_constraint('uq_manager_user_id', type_='unique')
        batch_op.drop_constraint('uq_manager_employee_code', type_='unique')
        batch_op.drop_column('employee_code')
        batch_op.drop_column('department')
        batch_op.drop_column('user_id')
    
    # Drop refresh_token table
    op.drop_index(op.f('ix_refresh_token_token'), table_name='refresh_token')
    op.drop_index(op.f('ix_refresh_token_id'), table_name='refresh_token')
    op.drop_table('refresh_token')
    # ### end Alembic commands ###
